/** One-shot Windows portable packager using official prebuilt binaries (no compile). */

export type PrebuiltChannel = "stable" | "beta" | "dev" | "canary";
export type PrebuiltPlatform = "win64" | "win32";

export interface ChromeForTestingRelease {
  channel: string;
  version: string;
  revision: string;
  platform: PrebuiltPlatform;
  zipUrl: string;
  source: "chrome-for-testing";
}

export interface SnapshotRelease {
  platform: "Win_x64" | "Win";
  revision: string;
  zipUrl: string;
  source: "chromium-snapshot";
}

const CFT_JSON =
  "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json";

const SNAPSHOT_REDIRECT = "https://download-chromium.appspot.com/dl/Win_x64?type=snapshots";

type CftJson = {
  channels: Record<
    string,
    {
      channel: string;
      version: string;
      revision: string;
      downloads: {
        chrome?: { platform: string; url: string }[];
      };
    }
  >;
};

export async function fetchChromeForTesting(
  channel: PrebuiltChannel = "stable",
  platform: PrebuiltPlatform = "win64",
): Promise<ChromeForTestingRelease> {
  const res = await fetch(CFT_JSON);
  if (!res.ok) throw new Error(`無法讀取 Chrome for Testing 版本清單 (${res.status})`);
  const data = (await res.json()) as CftJson;
  const key =
    channel === "stable"
      ? "Stable"
      : channel === "beta"
        ? "Beta"
        : channel === "dev"
          ? "Dev"
          : "Canary";
  const ch = data.channels[key];
  if (!ch) throw new Error(`找不到 channel: ${key}`);
  const item = ch.downloads.chrome?.find((d) => d.platform === platform);
  if (!item?.url) throw new Error(`找不到 ${platform} 下載連結`);
  return {
    channel: ch.channel,
    version: ch.version,
    revision: ch.revision,
    platform,
    zipUrl: item.url,
    source: "chrome-for-testing",
  };
}

export async function fetchChromiumSnapshotRedirect(): Promise<SnapshotRelease> {
  // HEAD follows redirect to the actual GCS object
  const res = await fetch(SNAPSHOT_REDIRECT, { method: "HEAD", redirect: "follow" });
  const url = res.url || SNAPSHOT_REDIRECT;
  const m = url.match(/Win_x64\/(\d+)\//);
  return {
    platform: "Win_x64",
    revision: m?.[1] ?? "latest",
    zipUrl: url,
    source: "chromium-snapshot",
  };
}

export function generatePrebuiltPortableBat(opts: {
  packageDir: string;
  zipUrl: string;
  label: string;
  /** chrome-win64 folder name inside CfT zip; snapshot uses chrome-win */
  innerFolderHint?: string;
}): string {
  const dest = opts.packageDir.replace(/\//g, "\\");
  const zipName = "chromium-download.zip";
  return `@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul
title Chromium Portable Setup

REM ============================================================
REM  Chromium / Chrome-for-Testing → Windows Portable
REM  ${opts.label}
REM  Generated by Chromium Portable Builder
REM ============================================================

set "ROOT=%~dp0"
set "DEST=${dest}"
if "%DEST:~1,1%"==":" (
  REM absolute path ok
) else (
  set "DEST=%ROOT%${dest}"
)

set "APP=%DEST%\\App"
set "DATA=%DEST%\\Data"
set "ZIP=%TEMP%\\${zipName}"
set "EXTRACT=%TEMP%\\chromium-portable-extract"
set "URL=${opts.zipUrl}"

echo.
echo  [Chromium Portable]
echo  Target : %DEST%
echo  Source : %URL%
echo.

where curl >nul 2>&1
if errorlevel 1 (
  echo ERROR: 需要 curl.exe ^(Windows 10 1803+ 內建^)。
  echo 或改用瀏覽器下載 zip 後手動解壓到 App 資料夾。
  pause
  exit /b 1
)

if not exist "%DEST%" mkdir "%DEST%"
if not exist "%APP%" mkdir "%APP%"
if not exist "%DATA%" mkdir "%DATA%"

echo [1/4] 下載中 ^(約 150–200 MB，請稍候^)...
curl.exe -L --retry 3 --retry-delay 2 -o "%ZIP%" "%URL%"
if errorlevel 1 (
  echo ERROR: 下載失敗。請檢查網路或改用手動連結。
  pause
  exit /b 1
)

echo [2/4] 解壓縮...
if exist "%EXTRACT%" rmdir /s /q "%EXTRACT%"
mkdir "%EXTRACT%"
tar -xf "%ZIP%" -C "%EXTRACT%"
if errorlevel 1 (
  echo tar 失敗，改試 PowerShell Expand-Archive...
  powershell -NoProfile -Command "Expand-Archive -LiteralPath '%ZIP%' -DestinationPath '%EXTRACT%' -Force"
  if errorlevel 1 (
    echo ERROR: 無法解壓。請手動解壓 zip 到 %APP%
    pause
    exit /b 1
  )
)

echo [3/4] 複製到 App\\ ...
REM Chrome for Testing: chrome-win64\\  ; Chromium snapshot: chrome-win\\
set "SRC="
if exist "%EXTRACT%\\chrome-win64\\chrome.exe" set "SRC=%EXTRACT%\\chrome-win64"
if exist "%EXTRACT%\\chrome-win\\chrome.exe" set "SRC=%EXTRACT%\\chrome-win"
if exist "%EXTRACT%\\Chrome-bin\\chrome.exe" set "SRC=%EXTRACT%\\Chrome-bin"
if "%SRC%"=="" (
  for /d %%D in ("%EXTRACT%\\*") do (
    if exist "%%~fD\\chrome.exe" set "SRC=%%~fD"
  )
)
if "%SRC%"=="" if exist "%EXTRACT%\\chrome.exe" set "SRC=%EXTRACT%"

if "%SRC%"=="" (
  echo ERROR: 解壓後找不到 chrome.exe
  echo 請檢查 %EXTRACT%
  pause
  exit /b 1
)

echo  From: %SRC%
robocopy "%SRC%" "%APP%" /E /NFL /NDL /NJH /NJS /nc /ns /np >nul
set "RC=!ERRORLEVEL!"
if !RC! GEQ 8 (
  echo robocopy failed: !RC!
  pause
  exit /b 1
)
if not exist "%APP%\\chrome.exe" (
  echo ERROR: 複製後沒有 chrome.exe
  pause
  exit /b 1
)

echo [4/4] 寫入啟動器...
> "%DEST%\\ChromiumPortable.bat" (
  echo @echo off
  echo setlocal
  echo set "ROOT=%%~dp0"
  echo set "APP=%%ROOT%%App"
  echo set "DATA=%%ROOT%%Data"
  echo if not exist "%%DATA%%" mkdir "%%DATA%%"
  echo start "" "%%APP%%\\chrome.exe" --user-data-dir="%%DATA%%" --no-default-browser-check --disable-logging %%*
)

> "%DEST%\\README.txt" (
  echo Chromium Portable ^(Windows^)
  echo ============================
  echo.
  echo Run: ChromiumPortable.bat
  echo Profile data: Data\\
  echo Browser files: App\\
  echo.
  echo Built from: ${opts.label}
  echo Zip: ${opts.zipUrl}
  echo.
  echo Copy the whole folder to USB / another PC. No install required.
  echo This is NOT Google Chrome. Do not use Chrome trademarks when redistributing.
)

del /f /q "%ZIP%" >nul 2>&1
rmdir /s /q "%EXTRACT%" >nul 2>&1

echo.
echo  完成！
echo  啟動: %DEST%\\ChromiumPortable.bat
echo  整包資料夾可複製到 USB 使用。
echo.
start "" "%DEST%\\ChromiumPortable.bat"
pause
`;
}

export function generateManualPortableReadme(zipUrl: string, packageDir: string): string {
  return `Chromium Windows Portable — 手動 3 步
=====================================

1. 下載官方預編譯 zip：
   ${zipUrl}

2. 解壓，將內含 chrome.exe 的資料夾內容放到：
   ${packageDir}\\App\\

3. 在 ${packageDir}\\ 建立 ChromiumPortable.bat，內容：

@echo off
set "ROOT=%~dp0"
start "" "%ROOT%App\\chrome.exe" --user-data-dir="%ROOT%Data" --no-default-browser-check %*

然後雙擊 ChromiumPortable.bat 即可。設定會存在 Data\\，整包可搬到其他電腦。
`;
}
